# Generated by Django 6.0.5 on 2026-05-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='departments.department')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='unique_department_name_per_parent'), models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_root_department_name'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='department_name_not_empty')],
            },
        ),
    ]
