# Generated by Django 6.0.5 on 2026-05-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_name_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_root_department_name',
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_department_name_per_parent', nulls_distinct=False),
        ),
    ]
